#!/usr/bin/env php
<?php
ini_set('display_errors', 'On');
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/vendor/autoload.php');
require_once(__DIR__ . '/components/la/LAEnvironment.php');

putenv('YII_ENV=' . trim(file_get_contents(dirname(__FILE__) . '/config/mode.php')));

$env = new \app\components\LAEnvironment([
    __DIR__ . '/config'
        ]);

$env->setup();
$app = new yii\console\Application($env->console);
$exitCode = $app->run();
exit($exitCode);
